#!/usr/bin/env bash

readonly ACTION_INSTALL_PACMAN="INSTALL_PACMAN"
readonly ACTION_INSTALL_AUR="INSTALL_AUR"
readonly ACTION_CLONE="CLONE"
readonly ACTION_COPY="COPY"
readonly ACTION_MKDIR="MKDIR"
readonly ACTION_REMOVE="REMOVE"
readonly ACTION_BACKUP="BACKUP"
readonly ACTION_RESTORE="RESTORE"
readonly ACTION_INSTALL_FLATPAK="INSTALL_FLATPAK"