NAME="Example Desktop"

ID="example"

VERSION="0.1.0"

AUTHOR="Laosifu"

DESCRIPTION="Example desktop package"

PACKAGE_ROOT=""

SUPPORTED_DISTROS="
arch
endeavouros
cachyos
"

##################################################
# Package Managers
##################################################

PACMAN_PACKAGES="
hyprland
kitty
fish
starship
"

AUR_PACKAGES="
quickshell-git
papirus-icon-theme
"

##################################################
# Files
##################################################

COPY_ITEMS=""

##################################################
# Git repositories
##################################################

GIT_REPOSITORIES="
https://github.com/example/cartoon-shell.git|~/.config/quickshell/cartoon-shell
"

##################################################
# Services
##################################################

ENABLE_SERVICES="
"

DISABLE_SERVICES="
"

##################################################
# Commands
##################################################

PRE_INSTALL="
"

POST_INSTALL="
"

PRE_UNINSTALL="
"

POST_UNINSTALL="
"

##################################################
# Hooks
##################################################

REBOOT_REQUIRED=true
