# Desktop Package Manifest
NAME="Mailong2401 Desktop"
ID="mailong2401"
VERSION="1.0"
AUTHOR="Mailong2401"
DESCRIPTION="Hyprland desktop package"
SUPPORTED_DISTROS="arch endeavouros cachyos"
PACKAGE_ROOT="desktops/mailong2401/payload"
CONFIG_ROOT=".config"
ASSETS_ROOT="Pictures"
REBOOT_REQUIRED=true

PACMAN_PACKAGES="
base-devel
hyprland
kitty
brightnessctl
wl-clipboard
noto-fonts-cjk
nautilus
grim
slurp
xdg-desktop-portal-hyprland
jq
matugen
starship
fish
adw-gtk-theme
bc
qt6-multimedia
"

AUR_PACKAGES="
quickshell-git
sysstat
papirus-icon-theme
ttf-material-symbols-variable-git
otf-comicshanns-nerd
cava
qt6-5compat
"

COPY_ITEMS="
$CONFIG_ROOT|$HOME
$ASSETS_ROOT|$HOME
"

GIT_REPOSITORIES="
https://github.com/mailong2401/cartoon-shell.git|~/.config/quickshell/cartoon-shell
"
